language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t jihoonk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jihoonk/react-test npm test 

after_success:
  - docker build -t jihoonk/multi-client ./client
  - docker build -t jihoonk/multi-server ./server
  - docker build -t jihoonk/multi-worker ./worker
  - docker build -t jihoonk/multi-nginx ./nginx

  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push all images to docker hub
  - docker push jihoonk/multi-client 
  - docker push jihoonk/multi-server
  - docker push jihoonk/multi-worker
  - docker push jihoonk/multi-nginx