sudo: required
services:
  - docker

before_install:
  - docker build -t jihoonk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jihoonk/react-test npm test 

after_success:
  - docker build -t jihoonk/multi-client ./client
  - docker build -t jihoonk/multi-server ./server
  - docker build -t jihoonk/multi-worker ./worker
  - docker build -t jihoonk/multi-nginx ./nginx